"use client";

import React from "react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { motion } from "framer-motion";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-background text-on-surface">
      <Navbar />
      
      <main className="max-w-4xl mx-auto px-6 pt-32 pb-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-4xl md:text-5xl font-heading font-bold mb-4 tracking-tight uppercase">
            Privacy Policy
          </h1>
          <p className="text-text-secondary mb-12 font-medium">Last updated: March 13, 2026</p>

          <div className="prose prose-zinc dark:prose-invert max-w-none space-y-8 text-lg font-medium leading-relaxed">
            <section>
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>
              <p>
                We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mt-8 mb-4 uppercase tracking-tight">Interpretation and Definitions</h2>
              <h3 className="text-xl font-bold mt-6 mb-2">Interpretation</h3>
              <p>
                The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>
              <h3 className="text-xl font-bold mt-6 mb-2">Definitions</h3>
              <p>For the purposes of this Privacy Policy:</p>
              <ul className="list-disc pl-6 space-y-4">
                <li>
                  <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
                </li>
                <li>
                  <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                </li>
                <li>
                  <strong>Application</strong> refers to AlertyAi, the software program provided by the Company.
                </li>
                <li>
                  <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to AlertyAI.
                </li>
                <li>
                  <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                </li>
                <li>
                  <strong>Country</strong> refers to: Uttar Pradesh, India
                </li>
                <li>
                  <strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.
                </li>
                <li>
                  <strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.
                </li>
                <li>
                  <strong>Service</strong> refers to the Application or the Website or both.
                </li>
                <li>
                  <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.
                </li>
                <li>
                  <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
                </li>
                <li>
                  <strong>Website</strong> refers to AlertyAI, accessible from <a href="https://alwertyai.com" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">https://alwertyai.com</a>.
                </li>
                <li>
                  <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mt-8 mb-4 uppercase tracking-tight">Collecting and Using Your Personal Data</h2>
              <h3 className="text-xl font-bold mt-6 mb-2">Types of Data Collected</h3>
              <h4 className="text-lg font-bold mt-4 mb-2">Personal Data</h4>
              <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Email address</li>
                <li>First name and last name</li>
              </ul>

              <h4 className="text-lg font-bold mt-4 mb-2">Usage Data</h4>
              <p>Usage Data is collected automatically when using the Service.</p>
              <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mt-8 mb-4 uppercase tracking-tight">Use of Your Personal Data</h2>
              <p>The Company may use Personal Data for the following purposes:</p>
              <ul className="list-disc pl-6 space-y-4">
                <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mt-8 mb-4 uppercase tracking-tight">Retention of Your Personal Data</h2>
              <p>
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mt-8 mb-4 uppercase tracking-tight">Contact Us</h2>
              <p>If you have any questions about this Privacy Policy, You can contact us:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>By email: <a href="mailto:bindalshashank.89@gmail.com" className="text-primary hover:underline">bindalshashank.89@gmail.com</a></li>
                <li>By visiting this page on our website: <a href="https://alertyai.com/privacy" className="text-primary hover:underline">https://alertyai.com/privacy</a></li>
              </ul>
            </section>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  );
}
